[package]
name = "tokio_actix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
features = "0.10.0"
log = "0.4.14"
simplelog = "0.10.0"
tokio = { version = "1.11.0", features = ["full"] }
